mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework.routers import DefaultRouter
from proof import views as proof_views

router = DefaultRouter()
router.register('proof', proof_views.RegisterViewSet, basename='proof')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('proof.urls')),
    path('api/', include(router.urls)),
]

proof/urls.py
from django.urls import path
from . import views


app_name = "proof"

urlpatterns = [
    # ex: /proof/
    path('', views.registers_list, name='registers_list'),
    # ex: /proof/register/1/
    path('register/<int:pk>/', views.register_detail, name='register_detail'),
    # ex: /proof/register/new/
    path('register/new', views.register_new, name='register_new'),
    # ex: /proof/register/1/edit/
    path('register/<int:pk>/edit/', views.register_edit, name='register_edit'),
    # ex: /proof/register/1/delete
    path('register/<int:pk>/delete/',
         views.register_delete, name='register_delete'),
    # ex: /proof/cities/bogota
    path('cities/<str:city>', views.register_filter_by_city,
         name='register_filter_by_city'),
    # ex: /proof/cities/
    path('cities/', views.register_all_cities,
         name='register_all_cities'),
]

proof/models.py
from datetime import date
from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.


class Register(models.Model):
    first_name: str = models.CharField(max_length=200)
    last_name: str = models.CharField(max_length=200)
    email: str = models.EmailField(max_length=254)
    address: str = models.CharField(max_length=200)
    type_of_housing: str = models.CharField(max_length=200)
    country: str = models.CharField(max_length=200)
    department: str = models.CharField(max_length=200)
    city: str = models.CharField(max_length=200)
    comments: str = models.TextField()
    date_of_birth = models.DateField(default=date.today)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.first_name

proof/forms.py
from django import forms

from .models import Register


class RegisterForm(forms.ModelForm):

    class Meta:
        model = Register
        fields = ('first_name', 'last_name', 'email', 'address',
                  'type_of_housing', 'country', 'department', 'city', 'date_of_birth', 'comments')

proof/views.py
from datetime import date
from django.shortcuts import get_object_or_404, redirect, render
from .models import Register
from .forms import RegisterForm


from rest_framework import viewsets
from django.http import Http404
from rest_framework import status
from rest_framework.response import Response

# Clase 'RegisterSerializer'
from .serializers import RegisterSerializer

from django.db.models import Count

# Create your views here.


def registers_list(request):
    registers = Register.objects.all()
    return render(request, 'proof/register_list.html', {
        'registers': registers
    })


def register_detail(request, pk):
    register = get_object_or_404(Register, pk=pk)
    return render(request, 'proof/register_detail.html', {'register': register})


def register_new(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            count_of_cities = Register.objects.filter(
                city__iexact=form.cleaned_data["city"]).count()

            legal_age = date.today() - form.cleaned_data["date_of_birth"]

            if legal_age.days < 365*17:
                return render(request, 'proof/msg.html', {
                    "msg": "No es mayor de edad"
                })

            if count_of_cities < 3:
                register = form.save(commit=False)
                register.save()
                return redirect('proof:register_detail', pk=register.pk)
            else:
                return render(request, 'proof/msg.html', {
                    "msg": f'La ciudad {form.cleaned_data["city"]} ya ha sido registrada 3 veces.'
                })
    else:
        form = RegisterForm()
    return render(request, 'proof/register_edit.html', {'form': form})


def register_edit(request, pk):
    register = get_object_or_404(Register, pk=pk)
    if request.method == "POST":
        form = RegisterForm(request.POST, instance=register)
        if form.is_valid():
            register = form.save(commit=False)
            register.save()
            return redirect('proof:register_detail', pk=register.pk)
    else:
        form = RegisterForm(instance=register)
    return render(request, 'proof/register_edit.html', {'form': form})


def register_delete(request, pk):
    register = Register.objects.filter(pk=pk)
    register.delete()
    return render(request, 'proof/register_delete.html', {
        'msg': f'El registro con id {pk} fue eleminado.'
    })


def register_filter_by_city(request, city):
    count = Register.objects.filter(city__iexact=city).count()
    if count < 3:
        msg = f'Se puede registrar {3 - count} veces más esta ciudad.'
    else:
        msg = "No se puede registrar más veces esta ciudad."
    return render(request, 'proof/filter_cities_list.html', {
        'city': city,
        'count': count,
        'msg': msg,
    })


def register_all_cities(request):
    list_cities = Register.objects.select_related(
        'city').values('id', 'city', 'first_name').order_by('city')

    quantity_of_cities = list_cities.values('city').annotate(
        amount=Count('city')).order_by('-amount')
    return render(request, 'proof/cities_list.html', {
        'quantity_of_cities': quantity_of_cities
    })


class RegisterViewSet(viewsets.ModelViewSet):

    queryset = Register.objects.all().order_by('id')
    serializer_class = RegisterSerializer

proof/templates/proof/base.html
{% load static %}

<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext"
      rel="stylesheet"
      type="text/css"
    />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'css/proof.css' %}" />
  </head>
  <body class="w-full min-h-screen p-4">
    <div class="w-full p-4 mb-2 bg-yellow-100 rounded-xl">
      <h1 class="uppercase text-center text-3xl">
        <a href={% url 'proof:registers_list' %}>App Registro</a>
      </h1>
      <div class="w-full">
        <a
          href="{% url 'proof:register_new' %}"
          class="px-4 py-2 bg-yellow-200 rounded-xl hover:shadow-md hover:bg-yellow-300"
          ><span class="">➕</span> Nuevo Registro</a
        >
        <a
        href="{% url 'proof:register_all_cities' %}"
        class="px-4 py-2 bg-yellow-200 rounded-xl hover:shadow-md hover:bg-yellow-300"
        ><span class="">🏙</span> Tabla de Ciudades</a
      >
      </div>
    </div>
    <div class="w-full">{% block content %} {% endblock %}</div>
  </body>
</html>

proof/templates/proof/cities_list.html
{% extends 'proof/base.html' %} {% block content %}
<h3 class="px-4 py-2 my-2 rounded-xl bg-red-100 text-2xl">Registro por ciudades: </h3>
<div class="w-full p-4 mb-2 bg-blue-50 rounded-xl flex flex-col justify-center items-center">
  <table class="w-96 border-collapse border border-slate-500">
    <thead>
      <tr>
        <th class="px-4 py-2 border border-slate-600 bg-gray-300">
          Ciudades
        </th>
        <th class="px-4 py-2 border border-slate-600 bg-gray-300">
          Registros
        </th>
      </tr>
    </thead>
    <tbody>
      {% for register_city in quantity_of_cities  %}
        <tr>
          <td class="px-2 py-1 border border-slate-700">
            {{ register_city.city }}
          </td>
          <td class="px-2 py-1 border border-slate-700 text-center">
            {{ register_city.amount }}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

</div>
<div class="w-full p-4 mb-2 bg-blue-300/40 rounded-xl">
  <a
    class="px-4 py-2 rounded-xl bg-green-50 hover:bg-green-100 hover:shadow-md"
    href={% url 'proof:registers_list' %}
    ><span>🏡</span> Inicio</a
  >
</div>
{% endblock %}

proof/templates/proof/filter_cities_list.html
{% extends 'proof/base.html' %} {% block content %}
<div class="w-full p-4 mb-2 bg-gray-300 rounded-xl">
    <h3>Ciudad: {{ city }} </h3>
    <h2>Registrada: {{ count }}</h2>
    <h2>Mensaje: {{ msg }}</h2>
</div>
<div class="w-full p-4 mb-2 bg-blue-300/40 rounded-xl">
  <a
    class="px-4 py-2 rounded-xl bg-green-50 hover:bg-green-100 hover:shadow-md"
    href={% url 'proof:registers_list' %}
    ><span>🏡</span> Inicio</a
  >
</div>
{% endblock %}

proof/templates/proof/msg.html
{% extends 'proof/base.html' %} {% block content %}
<div class="w-full p-4 mb-2 bg-gray-300 rounded-xl">
    <h2>Mensaje: {{ msg }}</h2>
</div>
<div class="w-full p-4 mb-2 bg-blue-300/40 rounded-xl">
  <a
  class="px-4 py-2 rounded-xl bg-green-50 hover:bg-green-100 hover:shadow-md"
  href={% url 'proof:registers_list' %}
  ><span>🏡</span> Inicio</a
>
</div>
{% endblock %}

proof/templates/proof/register_delete.html
{% extends 'proof/base.html' %} {% block content %}
<div class="w-full p-4 mb-2 bg-gray-300 rounded-xl">
  <h2>{{ msg }}</h2>
</div>
<div class="w-full p-4 mb-2 bg-blue-300/40 rounded-xl">
  <a
    class="px-4 py-2 rounded-xl bg-blue-400 hover:bg-blue-500 hover:shadow-md"
    href={% url 'proof:registers_list' %}
    >Inicio</a
  >
</div>
{% endblock %}

proof/templates/proof/register_detail.html
{% extends 'proof/base.html' %} {% block content %}
<div class="w-full p-4 mb-2 bg-blue-300 rounded-xl">
  <h2>Detalle Usuario Registrado</h2>
</div>
<div class="w-full">
  <div class="w-full p-2 mb-2 bg-blue-50 rounded-xl">
    <p>Nombre: {{ register.first_name }}</p>
    <p>Apellido: {{ register.last_name }}</p>
    <p>Fecha de Nacimiento: {{ register.date_of_birth }}</p>
    <p>Email: {{ register.email }}</p>
    <p>Tipo de Vivienda: {{ register.type_of_housing }}</p>
    <p>Pais: {{ register.country }}</p>
    <p>Departamento: {{ register.department }}</p>
    <p>Ciudad: {{ register.city }}</p>
    <p>Comentarios: {{ register.comments }}</p>
    <p>Fecha de Creación: {{ register.created_date }}</p>
  </div>
</div>
<div class="w-full p-4 mb-2 bg-blue-300/40 rounded-xl">
  <a
    class="px-4 py-2 rounded-xl bg-green-50 hover:bg-green-100 hover:shadow-md"
    href={% url 'proof:registers_list' %}
    ><span>🏡</span> Inicio</a
  >
  <a
    class="px-4 py-2 rounded-xl bg-blue-400 hover:bg-blue-500 hover:shadow-md"
    href="{% url 'proof:register_edit' pk=register.pk %}"
    ><span class="">📝</span> Editar Registro</a
  >
  <a
    class="px-4 py-2 rounded-xl bg-red-300 hover:bg-red-400 hover:shadow-md"
    href="{% url 'proof:register_delete' pk=register.pk %}"
    ><span class="">X</span> Eliminar Registro</a
  >
</div>
{% endblock %}

proof/templates/proof/register_edit.html
{% extends 'proof/base.html' %} {% block content %}
<div class="w-full p-4 mb-2 bg-green-50 rounded-xl">
  <h2>Formulario de Registro</h2>
</div>
<form method="POST" class="w-full p-4 bg-gray-100 rounded-xl">
  {% csrf_token %} {{ form.as_p }}
  <button
    type="submit"
    class="px-4 py-2 my-2 rounded-xl bg-blue-100 hover:shadow-md hover:bg-blue-200"
  >
    Guardar
  </button>
</form>
<div class="w-full p-4 mb-2 bg-blue-300/40 rounded-xl">
  <a
    class="px-4 py-2 rounded-xl bg-green-50 hover:bg-green-100 hover:shadow-md"
    href={% url 'proof:registers_list' %}
    ><span>🏡</span> Inicio</a
  >
</div>
{% endblock %}

proof/templates/proof/register_list.html
{% extends 'proof/base.html' %} {% block content %}
<div class="w-full p-4 bg-blue-300 rounded-xl">
  <h2>Lista de Usuarios</h2>
</div>
{% for register in registers %}
<dir class="w-full p-1">
  <div class="w-full p-4 bg-blue-50 rounded-xl">
    <a
      href="{% url 'proof:register_detail' pk=register.pk %}"
      class="px-4 py-1 bg-blue-200 rounded-md hover:bg-blue-300"
      >Identificador: {{ register.id }}</a
    >
    <p>Nombre: {{ register.first_name }}</p>
    <p>Apellido: {{ register.last_name }}</p>
    <p>Email: {{ register.email }}</p>
    <a
      href="{% url 'proof:register_filter_by_city' city=register.city %}"
      class="px-4 py-1 bg-green-300 rounded-md hover:bg-green-400"
      >City: {{ register.city }}</a
    >
  </div>
</dir>
{% endfor %} {% endblock %}